from PyQt5.QtGui import QFont, QIcon


def icons_dash_buttom(self):
    # Configurar íconos de botones
    self.bt_minimizar.setIcon(QIcon("img/minus.svg"))
    self.bt_restaurar.setIcon(QIcon("img/chevron-up.svg"))
    self.bt_maximizar.setIcon(QIcon("img/chevron-down.svg"))
    self.bt_cerrar.setIcon(QIcon("img/x.svg"))
    self.btn_inventory.setIcon(QIcon("img/my-business.png"))
    self.btn_icon.setIcon(QIcon("img/icon.png"))
    self.btn_client.setIcon(QIcon("img/client.png"))
    self.btn_invoice.setIcon(QIcon("img/invoice.png"))
    self.btn_user.setIcon(QIcon("img/user_.png"))
    self.g_income.setIcon(QIcon("img/grafico.png"))
    self.g_expenses.setIcon(QIcon("img/decreciente.png"))
    self.btn_pdf.setIcon(QIcon("img/pdf-file.png"))
    self.btn_provider.setIcon(QIcon("img/provider.png"))
    self.btn_transaction.setIcon(QIcon("img/transaction.png"))
    self.g_transaction.setIcon(QIcon("img/analytics.png"))
    self.btn_project.setIcon(QIcon("img/project.png"))
    self.btn_sell.setIcon(QIcon("img/send.png"))
    self.btn_investement.setIcon(QIcon("img/income.png"))
    self.g_investement.setIcon(QIcon("img/line-chart.png"))
    self.btn_task.setIcon(QIcon("img/homework.png"))
    self.btn_goal.setIcon(QIcon("img/growth.png"))
    self.btn_gain.setIcon(QIcon("img/g_gain.png"))
    self.btn_calculate_gain.setIcon(QIcon("img/calculate_gain.png"))
    self.btn_business.setIcon(QIcon("img/almacenamiento-de-datos.png"))
    self.btn_report.setIcon(QIcon("img/reporte.png"))
    self.btn_address.setIcon(QIcon("img/maps-and-flags.png"))
    self.btn_maps.setIcon(QIcon("img/map.png"))
    self.btn_employee.setIcon(QIcon("img/teamwork.png"))
    self.btn_calendar.setIcon(QIcon("img/calendar.png"))
